all: evidence sum squares positives millionaire stringtodecimal replace

evidence: hw3.c hw3_evidence.c
	gcc -Wall -g -o evidence hw3.c hw3_evidence.c

sum: hw3.c sum.c
	gcc -Wall -g -o sum hw3.c sum.c

squares: hw3.c squares.c
	gcc -Wall -g -o squares hw3.c squares.c

positives: hw3.c positives.c
	gcc -Wall -g -o positives hw3.c positives.c

millionaire: hw3.c millionaire.c
	gcc -Wall -g -o millionaire hw3.c millionaire.c

stringtodecimal: hw3.c stringtodecimal.c
	gcc -Wall -g -o stringtodecimal hw3.c stringtodecimal.c

replace: hw3.c replace.c
	gcc -Wall -g -o replace hw3.c replace.c

clean:
	rm evidence sum squares positives millionaire stringtodecimal replace
