all: hw2_evidence sumcubes ladder stairs basetodecimal

hw2_evidence: hw2.c hw2_evidence.c
	gcc -Wall -o hw2_evidence hw2.c hw2_evidence.c -lm

sumcubes: hw2.c sumcubes.c
	gcc -Wall -o sumcubes hw2.c sumcubes.c -lm

ladder: hw2.c ladder.c
	gcc -Wall -o ladder hw2.c ladder.c -lm

stairs: hw2.c stairs.c
	gcc -Wall -o stairs hw2.c stairs.c -lm

basetodecimal: hw2.c basetodecimal.c
	gcc -Wall -o basetodecimal hw2.c basetodecimal.c -lm

clean:
	rm hw2_evidence sumcubes ladder stairs basetodecimal
